-- MySQL Script generated by MySQL Workbench
-- Wed Sep 11 20:42:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maintenance` (
  `id_maintenance` INT NOT NULL AUTO_INCREMENT,
  `attachment_id_attachment` INT NOT NULL,
  `maintenance_type` INT NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `creation_date` TIMESTAMP NULL DEFAULT NULL,
  `delivery_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_maintenance`),
  INDEX `fk_maintenance_attachment1_idx` (`attachment_id_attachment` ASC) VISIBLE,
  CONSTRAINT `fk_maintenance_attachment1`
    FOREIGN KEY (`attachment_id_attachment`)
    REFERENCES `mydb`.`attachment` (`id_attachment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`laboratory_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`laboratory_item` (
  `id_laboratory_item_heritage` INT NOT NULL AUTO_INCREMENT,
  `maintenance_id_maintenance` INT NOT NULL,
  `name_item` VARCHAR(250) NOT NULL,
  `brand` VARCHAR(250) NULL DEFAULT NULL,
  `model` VARCHAR(250) NULL DEFAULT NULL,
  `serial_number` VARCHAR(250) NULL DEFAULT NULL,
  `invoice_number` VARCHAR(100) NULL DEFAULT NULL,
  `entry_date` DATE NULL DEFAULT NULL,
  `next_calibration` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_laboratory_item_heritage`),
  INDEX `fk_laboratory_item_maintenance1_idx` (`maintenance_id_maintenance` ASC) VISIBLE,
  CONSTRAINT `fk_laboratory_item_maintenance1`
    FOREIGN KEY (`maintenance_id_maintenance`)
    REFERENCES `mydb`.`maintenance` (`id_maintenance`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attachment` (
  `id_attachment` INT NOT NULL AUTO_INCREMENT,
  `name_attachment` VARCHAR(250) NULL DEFAULT NULL,
  `path_attachment` VARCHAR(250) NULL DEFAULT NULL,
  `type_attachment` VARCHAR(50) NULL DEFAULT NULL,
  `size_attachment` BIGINT NULL DEFAULT NULL,
  `creation_date` TIMESTAMP NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `laboratory_item_id_laboratory_item_heritage` INT NOT NULL,
  PRIMARY KEY (`id_attachment`),
  INDEX `fk_attachment_laboratory_item1_idx` (`laboratory_item_id_laboratory_item_heritage` ASC) VISIBLE,
  CONSTRAINT `fk_attachment_laboratory_item1`
    FOREIGN KEY (`laboratory_item_id_laboratory_item_heritage`)
    REFERENCES `mydb`.`laboratory_item` (`id_laboratory_item_heritage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `laboratory_item_id_laboratory_item` INT NOT NULL,
  `title_category` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id_category`),
  INDEX `fk_category_laboratory_item1_idx` (`laboratory_item_id_laboratory_item` ASC) VISIBLE,
  CONSTRAINT `fk_category_laboratory_item1`
    FOREIGN KEY (`laboratory_item_id_laboratory_item`)
    REFERENCES `mydb`.`laboratory_item` (`id_laboratory_item_heritage`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(250) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`user_loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_loan` (
  `iduser_loan` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `email` VARCHAR(100) NULL,
  `rna` VARCHAR(10) NULL,
  `empresa` VARCHAR(200) NULL,
  `cracha` VARCHAR(20) NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`iduser_loan`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `rna_UNIQUE` (`rna` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `cracha_UNIQUE` (`cracha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loan` (
  `id_loan` INT NOT NULL AUTO_INCREMENT,
  `loan_date` TIMESTAMP NOT NULL,
  `return_date` TIMESTAMP NULL DEFAULT NULL,
  `status` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  `user_loan_iduser_loan` INT NOT NULL,
  PRIMARY KEY (`id_loan`),
  INDEX `fk_loan_user1_idx` (`user_id_user` ASC) VISIBLE,
  INDEX `fk_loan_user_loan1_idx` (`user_loan_iduser_loan` ASC) VISIBLE,
  CONSTRAINT `fk_loan_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_user_loan1`
    FOREIGN KEY (`user_loan_iduser_loan`)
    REFERENCES `mydb`.`user_loan` (`iduser_loan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`loan_has_laboratory_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`loan_has_laboratory_item` (
  `loan_id_loan` INT NOT NULL,
  `laboratory_item_id_laboratory_item` INT NOT NULL,
  PRIMARY KEY (`loan_id_loan`, `laboratory_item_id_laboratory_item`),
  INDEX `fk_loan_has_laboratory_item_laboratory_item1_idx` (`laboratory_item_id_laboratory_item` ASC) VISIBLE,
  INDEX `fk_loan_has_laboratory_item_loan_idx` (`loan_id_loan` ASC) VISIBLE,
  CONSTRAINT `fk_loan_has_laboratory_item_laboratory_item1`
    FOREIGN KEY (`laboratory_item_id_laboratory_item`)
    REFERENCES `mydb`.`laboratory_item` (`id_laboratory_item_heritage`),
  CONSTRAINT `fk_loan_has_laboratory_item_loan`
    FOREIGN KEY (`loan_id_loan`)
    REFERENCES `mydb`.`loan` (`id_loan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `laboratory_item_id_laboratory_item` INT NOT NULL,
  `building` VARCHAR(250) NULL DEFAULT NULL,
  `room` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_location`),
  INDEX `fk_location_laboratory_item1_idx` (`laboratory_item_id_laboratory_item` ASC) VISIBLE,
  CONSTRAINT `fk_location_laboratory_item1`
    FOREIGN KEY (`laboratory_item_id_laboratory_item`)
    REFERENCES `mydb`.`laboratory_item` (`id_laboratory_item_heritage`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
